### ISSUE TITLE
Enhancement: Some Azerbaijani letters are displayed incorrectly

### ISSUE THREAD

**Issue by Maharramoff** [appristas/frontend.az#15]
**Description**
 On the website some letters like _(Ə, Ş)_ are displayed incorrectly. More precisely, their sizes. 

**Steps To Reproduce**
    1. Launch Chrome Browser.
    2. Open the website.
    3. Go to the about page.

**Expected behavior**
It would be nice to change the _Roboto_ font to something more appropriate - e.g. _Helvetica_.

**Screenshots**
![letters](https://user-images.githubusercontent.com/9804406/54722978-6fcac400-4b7f-11e9-8d47-14a975d29220.png)

**Device Information:**
 - Google Chrome
 - Version: 72.0.3626.121

**Comment by GasimGasimzada** [comment]
Are you on Windows? I am currently checking it in macOS and the fonts look like the following. :

<img width="515" alt="Screen Shot 2019-03-21 at 2 50 23 AM" src="https://user-images.githubusercontent.com/807231/54724363-482a2a80-4b84-11e9-96d8-c29e275d3edf.png">

**Comment by Maharramoff** [comment]
> Are you on Windows? 

Yep. This is most likely due to the browser. And take into account that most people use chrome.

**Comment by GasimGasimzada** [comment]
The screenshot was from chrome on macOS. I need to investigate this to see what can cause the issue.

**Comment by GasimGasimzada** [comment]
Could you please check it on your device and browser to see if the fonts are shown properly? I checked it in Win10 w/ Chrome and it worked fine as far as I can tell but I want to be sure that it works fine before closing this issue.

**Comment by Maharramoff** [comment]
Apparently "ş" fixed, but "ə".
![letters-2](https://user-images.githubusercontent.com/9804406/54827229-f0e2a200-4cca-11e9-9344-78f605a0b9d0.png)

**Comment by GasimGasimzada** [comment]
For the time being, I am going to keep it as is as I would rather try to fix the issue in Roboto instead of changing the typeface. I am going to close the issue for now but will come back to it at a later time.
